Stat svc
Triapkin/java-explore-with-me pull request #1
Opened 2024-11-10 11:07 UTC by Triapkin

2024-11-10 19:34 UTC, z8q requested changes

2024-11-10 19:34 UTC, z8q commented on pom.xml
> +		<module>stats-service</module>
Пустой main модуль можно тоже создать на этом шаге
В нем пока будет только SpringBootApplication-класс, Dockerfile и pom.xml с зависимостями

2024-11-10 19:34 UTC, z8q commented on stats-service/pom.xml
> +        <maven.compiler.target>22</maven.compiler.target>
а в корневом поме - `<java.version>21</java.version>`
можно привести к одной версии

2024-11-10 19:34 UTC, z8q commented on stats-service/stats-server/pom.xml
> +    </parent>
тут парент должен указывать на pom stats-service
```
<parent>
        <artifactId>stats-service</artifactId>
        <groupId>ru.practicum</groupId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
```

2024-11-10 19:34 UTC, z8q commented on stats-service/stats-server/pom.xml
> +            <version>1.5.5.Final</version>
В корневом pom указана зависимость
```XML
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>3.3.2</version>
  <relativePath/>
 </parent>
```
spring-boot-starter-parent содержит информацию о версиях для определенного набора зависимостей
Список можно посмотреть [тут](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/3.3.2) в блоке Managed Dependencies (нужно пролистнуть немного вниз)

То есть зависимости из списка, которые есть в spring-boot-starter-parent мы можем указывать без версии, например как у тебя, в строках 72-75
```XML
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
```
Если хотим добавить зависимость, которой нет в spring-boot-starter-parent (mapstruct нет в паренте),
либо если хотим определить версию отличную от того, что предлагает spring-boot-starter-parent,
то ее можно указать с нужной версией в корневом поме, в блоке dependencyManagement
Это позволит в дочерних pom-ах добавлять зависимость без указания версии 
и еще мы сможем централизованно, в одном месте, управлять версиями

2024-11-10 19:34 UTC, z8q commented on stats-service/stats-server/src/main/java/ru/practicum/statsserver/controller/StatsController.java
> +    private StatsService statsService;
можно поставить final, так как значение будем создавать один раз, при создании контроллера
и тогда над классом надо будет заменить AllArgsConstructor на RequiredArgsConstructor

2024-11-10 19:34 UTC, z8q commented on stats-service/stats-dto/src/main/java/dto/ResponseDto.java
> +    @NotBlank
NotBlank больше применим к строкам,
для Long больше подойдет NotNull

2024-11-10 19:34 UTC, z8q commented on stats-service/stats-client/src/main/java/client/StatsClient.java
> +                .block();
Если фичи реактивности не использовать – Flux, Mono
Можно вместо WebClient использовать HttpClient (это больше пожелание)

2024-11-11 07:56 UTC, Triapkin commented on stats-service/pom.xml
> +        <maven.compiler.target>22</maven.compiler.target>
исправил

2024-11-11 07:57 UTC, Triapkin commented on stats-service/stats-server/pom.xml
> +    </parent>
исправил

2024-11-11 08:04 UTC, Triapkin commented on stats-service/stats-server/src/main/java/ru/practicum/statsserver/controller/StatsController.java
> +    private StatsService statsService;
исправил

2024-11-11 08:05 UTC, Triapkin commented on stats-service/stats-dto/src/main/java/dto/ResponseDto.java
> +    @NotBlank
исправил, изменил @NotBlank для строк

2024-11-11 10:48 UTC, Triapkin commented on pom.xml
> +		<module>stats-service</module>
добавил

2024-11-11 10:49 UTC, Triapkin commented on stats-service/stats-client/src/main/java/client/StatsClient.java
> +                .block();
HttpClient использовал уже, хотел попробовать WebClient

2024-11-11 18:08 UTC, z8q approved these changes

2024-11-11 18:08 UTC, z8q commented on main-service/pom.xml
> +    </parent>
Тут парентом будет

```XML
<parent>
   <artifactId>explore-with-me</artifactId>
   <groupId>ru.practicum</groupId>
   <version>0.0.1-SNAPSHOT</version>
</parent>
```

2024-11-11 18:08 UTC, z8q commented on pom.xml
> +                <version>1.5.5.Final</version>
Зависимости правильно прописаны
Еще можно вынести версии в properties, чтобы например два раза не писать 1.5.5.Final, можно использовать ссылку `${mapstruct}`

пример
```XML
<properties>
        <mapstruct>1.5.5.Final<mapstruct>
</properties>

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct}</version>
            </dependency>
        </dependencies>
</dependencyManagement>

```

2024-11-13 08:04 UTC, merged