Main svc
Triapkin/java-explore-with-me pull request #2
Opened 2024-11-18 19:35 UTC by Triapkin

2024-11-19 19:00 UTC, z8q requested changes

2024-11-19 19:00 UTC, z8q commented on main-service/src/main/java/ru/practicum/mainservice/service/RequestService.java
> +        eventRepository.save(event);
Мало вероятно, но может так случится, что requestRepository.save выполнится корректно, а запрос eventRepository.save упадет (таблицы нет, валидация не прошла или коннект к базе пропал или другие возможные ошибки). В этом случае сохраним request и не сохраним event

Если над методом поставить аннотацию Transactional, то в случае возникновения исключений в строке 105, для 104-й будет выполнен роллбек. 
В случае успеха, к базе будут применены все изменения, и в случае ошибок - не будет применено ни одного.
Аннотация Transactional оборачивает все наши операции с базой в методе в транзакцию.

С этой аннотацией не все просто, например, если вызывать transactional-метод внутри того же класса, то транзакция не будет создана.
Роллбек транзакций не происходит при checked-исключениях, их нужно дополнительно указывать в параметре `@Transactional(rollbackFor = { SomeCheckedException.class })`
Для методов, которые выполняют только чтение, можно применить Transactional(readOnly = true), будут применены оптимизации для работы с базой

Это не вся информация про аннотацию, можно еще посмотреть дополнительные источники
например
https://www.baeldung.com/transaction-configuration-with-jpa-and-springhttps://www.baeldung.com/transaction-configuration-with-jpa-and-spring

2024-11-19 19:00 UTC, z8q commented on main-service/src/main/java/ru/practicum/mainservice/service/EventService.java
> +            events = eventRepository.findAllByAnnotationContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndCategory_IdInAndPaidIsAndEventDateBeforeAndEventDateAfter(
если название метода выстраивается в сложный запрос, то бывает лучше переписать на обычный sql через `@Query`

2024-11-19 19:00 UTC, z8q commented on main-service/src/main/java/ru/practicum/mainservice/service/EventService.java
> +        if (newEventDto.getRequestModeration() == null) event.setRequestModeration(true);
тут по сути происходит продолжение маппинга

например задать createdOn можно подобным образом
`@Mapping(target = "createdOn", expression = "java(LocalDateTime.now())")`

для строк 61-63 можно использовать у Mapping параметр [qualifiedByName](https://www.baeldung.com/mapstruct-custom-mapper#costom-mapper)

для ConfirmedRequests можно использовать у Mapping параметр constant

user, category и location в целом, можно и тут засеттить, чтобы не передавать в toEvent

2024-11-19 19:00 UTC, z8q commented on main-service/src/main/java/ru/practicum/mainservice/repository/EventRepository.java
> +    Page<Event> findAllByAnnotationContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndCategory_IdInAndPaidIsAndEventDateBeforeAndEventDateAfter(
не тестировал (в названиях стобцов могут быть неточности), но с аннотацией Query запрос мог бы выглядеть подобным образом
```SQL
SELECT *
FROM your_table_name t
WHERE 
    (LOWER(t.annotation) LIKE LOWER('%your_search_term%') OR 
    LOWER(t.description) LIKE LOWER('%your_search_term%'))
    AND t.category_id IN (your_category_ids) 
    AND t.paid = your_paid_status 
    AND t.event_date < your_event_date_before 
    AND t.event_date > your_event_date_after;
```
это позволило бы уменьшить название метода

еще можно использовать аннотацию Param https://www.baeldung.com/spring-data-jpa-query#1-jpql-4

2024-11-19 19:51 UTC, Triapkin commented on main-service/src/main/java/ru/practicum/mainservice/service/RequestService.java
> +        eventRepository.save(event);
спасибо за подробный ответ, добавил @Transactional для этого метода

2024-11-19 20:10 UTC, Triapkin commented on main-service/src/main/java/ru/practicum/mainservice/service/EventService.java
> +        if (newEventDto.getRequestModeration() == null) event.setRequestModeration(true);
для ConfirmedRequests  не стал делать constant, EventFullDto возвращается и в других методах (getEvent, updateEvent etc), я так понимаю что constant всегда при маппинге будет возвращать 0.

2024-11-19 20:15 UTC, Triapkin commented on main-service/src/main/java/ru/practicum/mainservice/repository/EventRepository.java
> +    Page<Event> findAllByAnnotationContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndCategory_IdInAndPaidIsAndEventDateBeforeAndEventDateAfter(
спасибо, переписал на @Query

2024-11-20 19:04 UTC, z8q approved these changes

2024-11-20 19:22 UTC, merged